import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./types`.

export enum OrdersStatus {
    PENDING = "pending",
    ACCEPTED = "accepted",
    OUT_FOR_DELIVERY = "out_for_delivery",
    DELIVERED = "delivered",
    RETURNED = "returned"
}

export type Products = Models.Row & {
    name: string;
    has_tier_pricing: boolean;
    description: string | null;
    available: boolean;
    primary_image_id: string | null;
    tier_2_4kg_price: number | null;
    tier_5_9kg_price: number | null;
    tier_10kg_up_price: number | null;
    base_price_per_kg: number | null;
}

export type ProductImages = Models.Row & {
    file_id: string;
    product_id: string;
    is_primary: boolean | null;
}

export type Customers = Models.Row & {
    email: string | null;
    user_id: string;
    full_name: string;
    phone: string;
}

export type Orders = Models.Row & {
    address_id: string;
    customer_id: string;
    total_price: number;
    status: OrdersStatus;
    order_items: string;
    total_items_count: number | null;
    total_weight_kg: number | null;
    subtotal_before_discount: number | null;
    total_discount_amount: number | null;
    payment_method: string | null;
    transaction_id: string | null;
}

export type Addresses = Models.Row & {
    address_line: string;
    longitude: number;
    customer_id: string;
    latitude: number;
    order_id: string;
    maps_url: string | null;
    city: string | null;
}

export type OrderItems = Models.Row & {
    order_id: string;
    product_id: string;
    product_name: string;
    product_description: string | null;
    quantity_kg: number;
    bags_1kg: number | null;
    bags_5kg: number | null;
    bags_10kg: number | null;
    bags_25kg: number | null;
    price_per_kg_at_order: number;
    base_price_per_kg: number;
    tier_applied: string | null;
    discount_percentage: number | null;
    discount_amount: number | null;
    subtotal_before_discount: number;
    total_after_discount: number;
    notes: string | null;
}

export type DiscountManagement = Models.Row & {
    type: string;
    customer_id: string | null;
    customer_name: string | null;
    card_status: string | null;
    total_purchases: number | null;
    total_purchase_amount: number | null;
    eligible_for_extra_discount: boolean;
    extra_discount_percentage: number | null;
    rule_name: string | null;
    discount_percentage: number | null;
    rule_active: boolean;
    discount_code: string | null;
    code_status: string | null;
    used_in_order_id: string | null;
    code_generated_at: string | null;
    code_used_at: string | null;
    is_enabled: boolean;
    order_id: string;
}
